plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs 


title: De Vega Lab
description: Our group
url: https://devegagroup.github.io


# Navigation settings
nav_enabled: True
search_enabled: false



nav_external_links:
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=vqxvVxQAAAAJ
    hide_icon: false
  - title: Group's Github
    url: https://github.com/DeVegaGroup
    hide_icon: false

# Formatting
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme (optional: light, dark, or system)
color_scheme: light
